name: donNote
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - requests
  - pip:
      - google-genai
      - python-dotenv
      - supabase
      - flask
      - flask-cors
      - httpx
      - pathlib
